### ISSUE TITLE
Add the ability to splat into keyword arguments

### ISSUE THREAD

**Issue by itsdfish** [jonniedie/ComponentArrays.jl#117]
Hello,

As mentioned on [discourse](https://discourse.julialang.org/t/splat-componentarray-into-keyword-arguments/75003/3), it would be useful to splat a `ComponentArray` into the keyword argument of a function. Here is an example of the desired behavior:

```
using ComponentArrays

x = ComponentArray(a = 1, b = 2)

f(;a, b) = a + b

f(;x...)
```

**Comment by itsdfish** [comment]
@jonniedie, wow! Thanks for adding this so quickly.

By the way, I was wondering if this would be a slightly better test since it tests whether the values are correctly mapped to the keyword arguments:

```
kw_fun(; a, b) = a / b
x = ComponentArray(b=1, a=2)
@test merge(NamedTuple(), x) == NamedTuple(x)
@test kw_fun(; x...) == 2
```

**Comment by jonniedie** [comment]
Oh, good point. Yeah that probably would be better. Or even `a // b` to avoid potential floating-point issues with the end comparison.
