### ISSUE TITLE
Make NamedTuple(::ComponentArray) more AD friendly 

### ISSUE THREAD

**Issue by marius311** [jonniedie/ComponentArrays.jl#122]
Here's a version of [this](https://github.com/jonniedie/ComponentArrays.jl/blob/b1a7afcc3d10f5ac5401010728e7e653f6a20779/src/similar_convert_copy.jl#L63-L76) which doesn't mutate an array, hence works with Zygote:

```julia
function _namedtuple(x::ComponentVector)
    NamedTuple{keys(x)}(map(valkeys(x)) do key
        _namedtuple(getproperty(x, key))
    end)
end
```

And a test which otherwise fails with the latest release version:

```julia
@test ComponentArray(x=4,) == Zygote.gradient(ComponentArray(x=2,)) do c
    (;c...,).x^2
end[1]
```

Wanted to just suggest this here rather than PR since there's some stuff that function is doing (or seemed to before comments) that I wasn't sure about. If this is good, please feel free to commit directly.

**Comment by jonniedie** [comment]
Oh, this is great! Really speeds things up too.

**Comment by jonniedie** [comment]
Thanks!
