### ISSUE TITLE
issue a warning or error on constructing Axis with duplicate symbols

### ISSUE THREAD

**Issue by bgctw** [jonniedie/ComponentArrays.jl#130]
Currently, constructing an Axis from a Tuple of symbols silently ignores duplicate symbols and only records position of the last occurrence:
```
julia> Axis((:a,:a))
Axis(a = 2,)
```
What is the reason for this behavior?

My use case is attaching positions to an existing Vector: `ComponentVector([1,2],Axis((:a,:a)))`
I would expect at least a warning here.

**Comment by jonniedie** [comment]
Thanks for the issue! Fixed in v0.11.17
