### ISSUE TITLE
Challenges for arrays of arrays?

### ISSUE THREAD

**Issue by jlchan** [jonniedie/ComponentArrays.jl#142]
When trying to create a component array made of up (for example, two StructArrays with entries which are SVector), I get the following error:`ComponentArrays cannot currently contain arrays of arrays as elements.` Are there specific challenges to support for arrays of arrays that I could take a look at?

I am trying to create a linearly indexed array `u` for use in OrdinaryDiffEq.jl where I can access the individual fields `u.field_1`,`u.field_2`.

**Comment by jonniedie** [comment]
You can do:
```julia
u = ComponentArray(field_1 = rand(5), field_2 = rand(5))
u.field_1
u.field_2
```
or even do something more `StructArray`-like:
```julia
a_b =  [(a=rand(), b=rand()) for _ in 1:100]
u = ComponentArray(fields = a_b)
```
The only thing you can't do is something like:
```julia
u = ComponentArray(fields = [rand(5), rand(5)])
u.fields[1]
u.fields[2]
```
It's probably possible to support the third version, I just haven't implemented it because the first two versions tend to cover most use cases.

**Comment by jonniedie** [comment]
`ComponentArray`s can also have nested structure in the `StructArray` form:
```julia
abc = [(a=rand(), b=rand(), c=(a=rand(), b=rand())) for _ in 1:100]
u = ComponentArray(fields = abc)
u.fields.c.a    # Returns a vector of the `.c.a` properties of all `u.fields`
```

**Comment by jlchan** [comment]
Those are nice to know about!

My use case is that I have two existing StructArrays that I wanted to combine and label using ComponentArrays. I think I can use the workarounds you described for most of my use cases. thanks!
