### ISSUE TITLE
Scalar indexing of a GPU array error 

### ISSUE THREAD

**Issue by lungd** [jonniedie/ComponentArrays.jl#150]
Zygote complains with a `scalar indexing is disallowed error` with [#999c335](https://github.com/jonniedie/ComponentArrays.jl/commit/999c3353f9d90d08607fdfd86cd3428480bfe715).

My code does work without that change. Sorry, I don't have a MWE to share at the moment.
Maybe the problem could be that during the FW pass of my custom Lux model I move an array to the CPU before I use it to solve an ODE and then the solution back to the GPU?
In case it's impossible to tell what could cause the error, I can try to reduce my model to a MWE.

Feel free to close this issue if you think it's a duplicate of #126

**Comment by MilkshakeForReal** [comment]
If you have moved the array to the CPU how could it complain about scalar indexing? Please put together a MWE

**Comment by avik-pal** [comment]
@jonniedie any reason the CRC rrule for getproperty was added. It breaks compatibility with CuArrays. See https://github.com/avik-pal/Lux.jl/issues/92

**Comment by MilkshakeForReal** [comment]
The last update is for fixing #148  I opened 🥲. A few hours ago I was celebrating the fact that it got fixed.   Maybe we can try to figure out how to fix it while avoiding scalar indexing

**Comment by MilkshakeForReal** [comment]
The PR #151 will fix both.

**Comment by lungd** [comment]
Awesome. Thanks!
