### ISSUE TITLE
Document ComponentMatrix API

### ISSUE THREAD

**Issue by metanoid** [jonniedie/ComponentArrays.jl#17]
`ComponentMatrix` and `ComponentVector` are exported functions, but are not mentioned in the API documentation [here](https://jonniedie.github.io/ComponentArrays.jl/dev/api/)

**Comment by jonniedie** [comment]
You're right, these should have been documented (and have better constructor methods defined). I was just using them as aliases for dispatch, but it's nice to have them as constructors that do dimension checking as well, so I added that feature (with documentation, of course).
