### ISSUE TITLE
Circular dependency introduced in v0.15.18

### ISSUE THREAD

**Issue by jonniediegelman** [jonniedie/ComponentArrays.jl#279]
@avik-pal , I noticed that since [this PR](https://github.com/jonniedie/ComponentArrays.jl/pull/276) went through, I've been getting this warning:
```julia
┌ Warning: Circular dependency detected. Precompilation will be skipped for:
│   ComponentArraysConstructionBaseExt [446cf315-a25e-5b5e-ab26-fb2b63960ee9]
│   ComponentArraysAdaptExt [790f4daf-a4cd-52c9-af90-2799ce9781e5]
└ @ Pkg.API ~/.julia/juliaup/julia-1.10.6+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Pkg/src/API.jl:127
```
Any idea what is causing that?

**Comment by jonniediegelman** [comment]
I unfortunately don't know enough about how the package extensions work to know how circular dependencies can be introduced. Just looking at those extension files, I can't see anything immediately wrong.

**Comment by avik-pal** [comment]
I see what happened. Functors.jl started using ConstructionBase as a default dep in v0.5. Since we have ConstructionBase in ext and Functors as a main dep, it causes this.

I will make a PR moving ConstructionBase to main dep since it is anyways being loaded as a default
