### ISSUE TITLE
Arguably identical CAs raising StackOverflowError on promote_rule()

### ISSUE THREAD

**Issue by dcabecinhas** [jonniedie/ComponentArrays.jl#34]
```julia
julia> using ComponentArrays

julia> x1 = ComponentArray(a=[1.1,2.1], b=[0.1])
ComponentVector{Float64}(a = [1.1, 2.1], b = [0.1])

julia> x2 = ComponentArray(a=[1.1,2.1], b=0.1)
ComponentVector{Float64}(a = [1.1, 2.1], b = 0.1)

julia> typeof(x1)
ComponentArray{Float64,1,Array{Float64,1},Tuple{Axis{(a = 1:2, b = 3:3)}}}

julia> typeof(x2)
ComponentArray{Float64,1,Array{Float64,1},Tuple{Axis{(a = 1:2, b = 3)}}}

julia> promote_rule(Axis{(a = 1:2, b = 3:3)},Axis{(a = 1:2, b = 3)})
ERROR: StackOverflowError:
Stacktrace:
 [1] promote_rule(::Type{Axis{(a = 1:2, b = 3:3)}}, ::Type{Axis{(a = 1:2, b = 3)}}) at /Users/dcabecinhas/.julia/packages/ComponentArrays/Z6vz2/src/similar_convert_copy.jl:60
 [2] promote_type(::Type{Axis{(a = 1:2, b = 3:3)}}, ::Type{Axis{(a = 1:2, b = 3)}}) at ./promotion.jl:223
 ... (the last 2 lines are repeated 39990 more times)
 [79983] promote_rule(::Type{Axis{(a = 1:2, b = 3:3)}}, ::Type{Axis{(a = 1:2, b = 3)}}) at /Users/dcabecinhas/.julia/packages/ComponentArrays/Z6vz2/src/similar_convert_copy.jl:60


```

**Comment by jonniedie** [comment]
Yeah, this should error, but in a clearer way. Since `x1.b` is is a vector and `x2.b` is a scalar, they can't be the same type (scalarness/vectorness is respected, just like if `x1` and `x2` were named tuples or structs).

But since this probably came from something broadcast-related that shouldn't throw an error (like `x1 + x2`), it should be handled upstream in the broadcasting promotion (basically, fall back to the inner arrays if the `Axis` types can't be resolved). Let me see if I can get an easy fix in for that.

**Comment by jonniedie** [comment]
Or I guess it shouldn't error, but fall back to `FlatAxis`.

**Comment by dcabecinhas** [comment]
I encountered the issue because `u0` and `du` were slightly different in an ODE. In that situation reverting to `FlatAxis` would solve the problem.

There might be other situations where users would prefer to be alerted to a component mismatch instead of losing the components but reverting to `FlatAxis` seems the more useful behavior.

**Comment by jonniedie** [comment]
In the new update, I've got it so it just falls back to FlatAxis. But yeah, a warning to go along with it would probably be nice too. It might make for some pretty tricky bugs if you misspell a key and it just falls back to a plain array. Ideally, making a new `ComponentArray` with the same type as another one would be done with `similar` or `copy`, but there are probably some cases where that wouldn't work.
