### ISSUE TITLE
Taking cats seriously

### ISSUE THREAD

**Issue by jonniedie** [jonniedie/ComponentArrays.jl#45]
- [x] `vcat` of two `ComponentVector`s where they share any of the same component names should become a plain `Array`
- [ ] Need `cat` defined
- [x] Faster `cat`s, if possible

**Comment by jonniedie** [comment]
cc26c7f adds faster `vcat` and `hcat` reductions.

**Comment by jonniedie** [comment]
Apparently the first check box was already done some time ago.

**Comment by baggepinnen** [comment]
I'm wondering how to write generic code that concatenates ComponentMatrics. Consider concatenating two linear systems (source in ControlSystems: https://github.com/JuliaControl/ControlSystems.jl/blob/17e78c10ddaa8dbdff672af26eff313e65de904a/src/types/StateSpace.jl#L227)
```julia
    A = [s1.A                   zeros(T, nstates(s1), nstates(s2));
         zeros(T, nstates(s2), nstates(s1))        s2.A]
```
Here' the call to `zeros` produces a standard `Array` which loses the names of the states if `s1.A` and `s2.A` are `ComponentArrays`. Ideally, methods should be written completely generically, i.e., without knowing about ComponentArrays, but still propagate the correct type information. I.e., it would be nice if all operations `+,-,*,/` between linear systems could be generically written and used with ComponentArrays to keep track of the names of states.

**Comment by baggepinnen** [comment]
`vcat` and `hcat` do not seem to work for `CompoenentMatrix`, only for `ComponentVector`

**Comment by jonniedie** [comment]
I'll try to get to this one tonight. It's going to take a little work.

**Comment by jonniedie** [comment]
@baggepinnen I think 04387cf81082211f2007d07792754c3e2f9b7f16 should do the trick. Let me know if you run into any bugs with it. I tried to cover as much as I could with the tests, but there are a lot of ways to bugs to get in here.

**Comment by jonniedie** [comment]
Ugh, nevermind. This broke something on Julia versions <= v1.4. I'll have to dig into that.
