### ISSUE TITLE
Broadcasting bug

### ISSUE THREAD

**Issue by baggepinnen** [jonniedie/ComponentArrays.jl#51]
https://github.com/jonniedie/ComponentArrays.jl/blob/85f99a369b2cf7204fabe30ed5a458af18d5b349/src/broadcasting.jl#L74
The line above creates problems in the situation the comment above it claims that it improves. If `f` changes the type of the numerical values, they will not fit in `new_data`.

**Comment by jonniedie** [comment]
Thanks! That was a good catch.

Closed by 5c4242e.
