### ISSUE TITLE
Silently fails with Sundials

### ISSUE THREAD

**Issue by marius311** [jonniedie/ComponentArrays.jl#53]
It looks like if you use ComponentArrays with Sundials, it "succeeds" but the solution is wrong, eg here it doesn't move from the initial value even though the answer should be `e`. 

```julia
julia> using DiffEqBase, Sundials, ComponentArrays

julia> prob = ODEProblem((u,p,t)->u, ComponentArray(x=ones(10)), (0.,1.));

julia> sol = solve(prob, CVODE_BDF(linear_solver=:BCG), reltol=1e-3);

julia> sol(1)
ComponentVector{Float64}(x = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
```

This is Julia 1.5.2, ComponentArrays v0.8.7, and Sundials v4.2.6.

**Comment by jonniedie** [comment]
I don’t have access to a computer at the moment and this is a tough one to debug in Codespaces on my iPad, so I’ll have to give it a look tomorrow. This one looks like it might take some digging.

**Comment by jonniedie** [comment]
Alright, here's a quick patch that will work until I figure out the right way to do this:

```julia
Base.convert(::Type{Sundials.NVector}, x::ComponentArray) = Sundials.NVector(getdata(x))
```

**Comment by jonniedie** [comment]
Figured it out. Was missing a method to explicitly convert to `Array`. Which is kinda weird because it was doing the conversion to `NVector` directly correctly even without either `convert` method defined.
