### ISSUE TITLE
Single element CA throws an error

### ISSUE THREAD

**Issue by amrods** [jonniedie/ComponentArrays.jl#61]
Trying to construct any of these two objects throws an error:
```
ca1 = ComponentArray(x = 5)
ERROR: MethodError: no method matching ComponentArray(::Int64, ::Tuple{Axis{(x = 1,)}})

ca2 = ComponentArray(x = [5])
ERROR: MethodError: no method matching ComponentArray(::Int64, ::Tuple{Axis{(x = 1:1,)}})
```
is that expected?
(declaring the type of the CA as `Int` solves the issues though)

**Comment by dcabecinhas** [comment]
I'm having a similar problem with 

```julia
V = ComponentArray(A = 1,)
ERROR: MethodError: no method matching ComponentArray(::Int64, ::Tuple{Axis{(A = 1,)}})```

Seems to have been introduced with 0.8.12 as it was running fine before.

**Comment by jonniedie** [comment]
Oh, it looks like this was tied to what I did in #59. I didn't consider that `reduce(vcat, data)` creates a scalar if there is only one  element in the array. Should be an easy enough fix.
