### ISSUE TITLE
Feature request: easier default field names

### ISSUE THREAD

**Issue by avonmoll** [jonniedie/ComponentArrays.jl#68]
This package is awesome. Would it be possible to support constructing a ComponentArray from a Dict? E.g. instead of
```julia
x = 1; y = 2; z = 3
v = [1, 2, 3, 4]
ca = ComponentArray(x=x, y=y, z=z, v=v)
```

We could do stuff like

```julia
using DrWatson: @dict
ca = ComponentArray(@dict x y z v)
```

Or skip the Dict stuff and have a macro that could be used as follows

```julia
ca = @componentarray x y z v
```

This would eliminate the need to explicitly name fields when constructing a ComponentArray when the contents are already defined in variables.

**Comment by jonniedie** [comment]
I think a constructor from a `Dict` is a good idea. You can already make `ComponentArray`s from `NamedTuple`s and you can make `NamedTuple`s from `Dict`s, so it makes sense that you should be able to make a `ComponentArray` directly from a `Dict`. That's a pretty easy add. I'll put that in tonight.

As for the syntax, if you're on Julia >= v1.5 you can already pretty much do that, you just need a semicolon before the arguments:

```julia
julia> using ComponentArrays

julia> x = 1; y = 2; z = 3;

julia> v = [1, 2, 3, 4];

julia> ca = ComponentArray(; x, y, z, v)
ComponentVector{Int64}(x = 1, y = 2, z = 3, v = [1, 2, 3, 4])
```
