### ISSUE TITLE
Unexpected `label2index` behavior

### ISSUE THREAD

**Issue by agerlach** [jonniedie/ComponentArrays.jl#74]
```julia
ca = ComponentArray(a = 1, aa = 2, ab = 3)
label2index(ca, "a") # [1,2,3]
label2index(ca, "aa") #[2]
```

I was expecting `label2index` to require a complete string match vs `startswith`. Is this what you intend? 

https://github.com/jonniedie/ComponentArrays.jl/blob/85f99a369b2cf7204fabe30ed5a458af18d5b349/src/plot_utils.jl#L88

I essentially require a way to get the index of a nested label. Is there a better option for this?

```julia
ca = ComponentArray(state = (x = 1.0, xdot = 2.0), control = 0.0)
idx = label2index(ca, "state.x") # returns [1,2] but desire just 1
```

I expect the current implementation is to support 
```julia
ca = ComponentArray(state = (x = 1.0, xdot = 2.0), control = 0.0)
idx = label2index(ca, "state") # returns [1,2] 
```

**Comment by agerlach** [comment]
This isn't typestable, but it implements the expected behavior
```julia
function label2idex(labs, str)
    idx = findall(startswith.(labs, str*"."))
    if !isempty(idx)
        return idx
    end
    idx2 = findfirst(l -> l .== str, labs)
end

**Comment by jonniedie** [comment]
I think we'll have to get regular expressions involved here because we have cases like this as well:

```julia
ca = ComponentArray(a = 1, aa = 2, ab = [5, 3])
```

**Comment by jonniedie** [comment]
Actually, here's a good stress test that (I think) hits everything we need to cover:
```julia
ca = ComponentArray(a=1, aa=ones(2), ab=[(a=1, aa=ones(2)), (a=1, aa=ones(2))], ac=(a=1, ab=ones(2,2)))
```
```julia
julia> labels(ca)
14-element Vector{String}:
 "a"
 "aa[1]"
 "aa[2]"
 "ab[1].a"
 "ab[1].aa[1]"
 "ab[1].aa[2]"
 "ab[2].a"
 "ab[2].aa[1]"
 "ab[2].aa[2]"
 "ac.a"
 "ac.ab[1,1]"
 "ac.ab[2,1]"
 "ac.ab[1,2]"
 "ac.ab[2,2]"
```

**Comment by jonniedie** [comment]
Matching for a `[` as well as a `.` seems to do the trick:
```julia
function label2idex(labs, str)
    idx = findall(startswith.(labs, Regex("$str(\\.|\\[)")))
    if !isempty(idx)
        return idx
    end
    idx2 = findall(l -> l .== str, labs)
end
```

**Comment by agerlach** [comment]
Yes, this is much nicer. 

Why use `findall` for `idx2` vs `findfirst`? Its a trivial amount of computation saves, but can't you gaurentee that  all elements from `label` are unique?

**Comment by jonniedie** [comment]
Yes you can. For type stability's sake and for simplicity, I figured it would be better to always return a `Vector{Int64}` no matter what.

**Comment by agerlach** [comment]
Just wrap in `[]`?
`idx2 = [findfirst(l -> l .== str, labs)]`

**Comment by jonniedie** [comment]
Haha, do'h. Yeah, that makes more sense. Let's go with that.

And actually the regex above fails for:
"ab[1].aa"

Making it
```julia
idx = findall(startswith.(labs, str * r"(\.|\[)"))
```
works better. I'm not sure why. Regular expressions are deep magic that I will never actually understand.

**Comment by agerlach** [comment]
Agreed
