### ISSUE TITLE
Error differentiating functions with in-place mutation

### ISSUE THREAD

**Issue by Antomek** [jonniedie/ComponentArrays.jl#78]
Hello,

Thank you for the work on this very useful project!

I am running into an issue where I cannot use `ComponentArray`s with a function which mutates its `du`.

As a MWE, running [this example](https://jonniedie.github.io/ComponentArrays.jl/stable/examples/DiffEqFlux/), but replacing

```julia
function dudt(u, p, t)
    @unpack L1, L2 = p
    return L2.W * tanh.(L1.W * u.^3 .+ L1.b) .+ L2.b
end
```

with

```julia
function dudt(du, u, p, t)
    @unpack L1, L2 = p
    du .= L2.W * tanh.(L1.W * u.^3 .+ L1.b) .+ L2.b
end
```

yields the error:
```julia
ERROR: LoadError: type TrackedArray has no field L1
```

Am I doing something wrong? Can this be fixed somehow?

**Comment by jonniedie** [comment]
Oh, that’s related to #37 . ReverseDiff wraps an `Tracked` array type around the `ComponentArray` and that’s what messes with things. I actually wrote a way to handle this [here](https://github.com/jonniedie/ComponentArrays.jl/issues/37#issuecomment-797663879), but I kinda forgot about it so I don’t remember whether it actually worked or not 😅. For now, you can try that out and see if it works for you. I’ll try to take a look at it again soon so it can actually make it into the package.

If that doesn’t work, you can use ForwardDiff (which might be slow for something like a neural ode) or switch to out-of-place and use Zygote (use `ax = getaxes(u)` then `du = ComponentArray(L2.W * tanh.(L1.W * u.^3 .+ L1.b) .+ L2.b, ax)` to make it work).

**Comment by bgroenks96** [comment]
I was just about to ask what the status of #37 is :D
