### ISSUE TITLE
Flattened arrays at the output of a DifferentialEquations solver

### ISSUE THREAD

**Issue by JordiBolibar** [jonniedie/ComponentArrays.jl#79]
I’m solving a PDE on a Matrix directly with ComponentArray, but I’m getting flattened solutions at the output (1-dimensional).

```
p = (Γ, Δx, Δy, η)
u₀ = ComponentArray(H=H₀, B=B) # H and B are Matrices with size (193, 189)
tspan = (0.0, 10.0)
# Create ODE problem based on the SIA
SIA_prob = ODEProblem(iceflow!, u₀, tspan, p)
# Solve the SIA 
SIA_sol = solve(SIA_prob, Tsit5())
```

And when I do:
`println(size(SIA_sol.u[end]))`
Instead of getting `(193, 189)`, I get:
`(72954,)`
Which corresponds to the two matrices contained in `u` (`H` and `B`), flattened and concatenated.

Is this an expected behaviour? Shouldn't the same dimensions from the input be preserved?

**Comment by JordiBolibar** [comment]
That worked. Thanks a lot @jonniedie!

**Comment by jonniedie** [comment]
No prob!
