### ISSUE TITLE
Axes not defined

### ISSUE THREAD

**Issue by baggepinnen** [jonniedie/ComponentArrays.jl#87]
I got
```julia
ax1 = Axis((; x1=1))
ax2 = Axis((; x2=1))
A1 = ComponentMatrix(zeros(1, 1), ax1, ax1)
A2 = ComponentMatrix(zeros(1, 1), ax2, ax2)
[A for A in [A1, A2]]

julia> [A for A in [A1, A2]]
ERROR: UndefVarError: Axes not defined
Stacktrace:
 [1] getaxes(#unused#::Type{ComponentMatrix{Float64}})
   @ ComponentArrays ~/.julia/packages/ComponentArrays/exfK6/src/componentarray.jl:276
 [2] convert(#unused#::Type{ComponentMatrix{Float64}}, x::ComponentMatrix{Float64})
   @ ComponentArrays ~/.julia/packages/ComponentArrays/exfK6/src/similar_convert_copy.jl:46
 [3] setindex!
   @ ./array.jl:839 [inlined]
 [4] copyto!(dest::Vector{ComponentMatrix{Float64}}, src::Tuple{ComponentMatrix{Float64}, ComponentMatrix{Float64}})
   @ Base ./abstractarray.jl:846
 [5] vect(::ComponentMatrix{Float64}, ::Vararg{Any, N} where N)
   @ Base ./array.jl:129
 [6] top-level scope
   @ REPL[24]:1

(@v1.6) pkg> st ComponentArrays
      Status `~/.julia/environments/v1.6/Project.toml`
  [b0b7db55] ComponentArrays v0.9.9
```
pointing to
https://github.com/jonniedie/ComponentArrays.jl/blob/master/src/componentarray.jl#L276
which is

**Comment by jonniedie** [comment]
There's a couple of issue here. First, my type annotations were just wrong. But after that, there's some weird type promotion of `Axes` going on that I'll have to figure out.

**Comment by jonniedie** [comment]
Oh I see, I wasn't even doing the promotion right here. I must have written that part a long time ago. I'm surprised it hasn't been an issue until now.

**Comment by jonniedie** [comment]
I remember now why I was doing promotion incorrectly. Getting `promote_rule`s to work with the weird values-as-types thing I have for `Axe`s was pretty difficult. I just gave up and defined `promote` explicitly. The problem is `[A for A in [A1, A2]]` bypasses `promote`, so now I'll have to figure out the correct way to handle it.
