### ISSUE TITLE
dev documentation broken

### ISSUE THREAD

**Issue by roflmaostc** [jonniedie/ComponentArrays.jl#93]
Hey,

[this](https://jonniedie.github.io/ComponentArrays.jl/dev/) errors currently.

Thanks,

Felix

**Comment by jonniedie** [comment]
Oh wow. It looks like my docs haven't been building since I made the switch to Github Actions. Thanks for the heads-up. I'll get this fixed.

**Comment by jonniedie** [comment]
Well I tried fixing it and ended up breaking the stable documentation as well. So at least things are consistent now.

**Comment by jonniedie** [comment]
Finally fixed by b2a42e3a92991c07c5bf78793b524798d54b539d
