### ISSUE TITLE
StackOverflow from getindex

### ISSUE THREAD

**Issue by baggepinnen** [jonniedie/ComponentArrays.jl#94]
The following line causes me a StackOverflow error on the latest master
https://github.com/jonniedie/ComponentArrays.jl/blob/2d3291bfcd970add20205890b1b2c0ccadc4fb73/src/componentindex.jl#L12

The error is not very helpful though..
```julia
julia> bodeplot(sys, w, hz=true)
ERROR: StackOverflowError:
Stacktrace:
 [1] getindex(::Matrix{ComplexF64}) (repeats 79984 times)
   @ ComponentArrays ~/.julia/packages/ComponentArrays/raUTp/src/componentindex.jl:12
```
most of the stack is missing. I also can't see how that line actually causes the error since it does not have the same signature as in the error, but perhaps you have a better feeling for it than I do. Note that no ComponentArrays were actually used in this particular example, `sys` was given by
```julia
using ControlSystems
julia> show_construction(sys)
A = [0.0 1.0 0.0 0.0 0.0 0.0; -2000.0 -4.0 1000.0 2.0 1000.0 2.0; 0.0 0.0 0.0 1.0 0.0 0.0; 100.0 0.2 -100.0 -0.2 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 1.0; 1000.0 2.0 0.0 0.0 -1000.0 -2.0]
B = [0.0; 1.0; 0.0; 0.0; 0.0; 0.0]
C = [0.0 1.0 0.0 0.0 0.0 0.0]
D = [0.0]
sys = ss(A,B,C,D)
```

**Comment by baggepinnen** [comment]
In fact, 
```
julia> [1 2; 3 4][]
ERROR: StackOverflowError:
Stacktrace:
 [1] getindex(::Matrix{Int64}) (repeats 79984 times)
   @ ComponentArrays ~/.julia/packages/ComponentArrays/raUTp/src/componentindex.jl:12
```

**Comment by jonniedie** [comment]
Oh geez. I forgot that
```julia
Base.getindex(A::AbstractArray, inds::ComponentIndex...) = 
```
will make a method for `getindex(::AbstractArray)`.

**Comment by baggepinnen** [comment]
Hmm, that did not occur to me either, but is of course obvious when you point it out ^^. Thanks for fixing :)
